/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-surface-variant": "#584237",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "surface-tint": "#9d4300",
        secondary: "#565e74",
        primary: "#9d4300",
        "tertiary-fixed-dim": "#f7be1d",
        outline: "#8c7164",
        "on-primary-fixed": "#341100",
        "primary-fixed-dim": "#ffb690",
        "inverse-primary": "#ffb690",
        "primary-container": "#f97316",
        "surface-variant": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#251a00",
        "tertiary-fixed": "#ffdf9a",
        "tertiary-container": "#c19300",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "secondary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#783200",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9ff",
        "primary-fixed": "#ffdbca",
        "on-primary": "#ffffff",
        "on-primary-container": "#582200",
        "on-tertiary-fixed-variant": "#5a4300",
        "secondary-fixed-dim": "#bec6e0",
        "outline-variant": "#e0c0b1",
        tertiary: "#785a00",
        "on-secondary-fixed-variant": "#3f465c",
        background: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#dae2fd",
        surface: "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#412f00",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "space-md": "1rem",
        "gutter-sm": "1rem",
        "margin-sm": "1rem",
        "space-sm": "0.5rem",
        margin: "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "gutter-lg": "2rem",
        "space-xs": "0.25rem",
        "margin-lg": "3rem",
      },
      fontFamily: {
        "headline-lg": ["Noto Sans KR", "Inter"],
        "label-md": ["Noto Sans KR", "Inter"],
        "body-sm": ["Noto Sans KR", "Inter"],
        "display-lg": ["Noto Sans KR", "Inter"],
        "display-lg-mobile": ["Noto Sans KR", "Inter"],
        "label-sm": ["Noto Sans KR", "Inter"],
        "headline-md": ["Noto Sans KR", "Inter"],
        "body-lg": ["Noto Sans KR", "Inter"],
        "label-lg": ["Noto Sans KR", "Inter"],
        "body-md": ["Noto Sans KR", "Inter"],
        "headline-lg-mobile": ["Noto Sans KR", "Inter"],
      },
      fontSize: {
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "0em", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
