// Real member data, sourced only from what was explicitly confirmed by the team.
// Age, gender, birthday and email are not published.
const MEMBERS = [
  {
    id: "himnae",
    name: "힘내",
    aka: null,
    roles: ["사장", "총관리자"],
    caption: "심심할 때 멤버구경하다가 자러가기",
    color: "#991835",
    colorLabel: "딛 와인색 / 버건디 레드",
    oneLiner: "잔부탁드립니다",
    links: [
      { label: "치지직", icon: "live_tv", url: "https://chzzk.naver.com/53aabce8d0ad942469385c79d9325785" },
      { label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@himnae" },
    ],
    image: "img/members/himnae.png",
    note: null,
  },
  {
    id: "bery",
    name: "베리",
    aka: "블루베리",
    roles: ["편집장", "편집", "멤버"],
    caption: null,
    color: "#0055FF",
    colorLabel: "비비드 블루",
    oneLiner: "24시간 365일 풀가동입니다",
    links: [
      { label: "치지직", icon: "live_tv", url: "https://chzzk.naver.com/4c31baa1c07fe4acc82ae135a5bd50d4" },
      { label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@베리의잡동사니" },
    ],
    image: "img/members/bery.png",
    note: null,
  },
  {
    id: "soyu",
    name: "소유",
    aka: null,
    roles: ["매니저", "멤버"],
    caption: null,
    color: "#FAFAF8",
    colorLabel: "하얀색",
    oneLiner: null,
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@kr_so_you" }],
    image: "img/members/soyu.png",
    note: null,
  },
  {
    id: "ino",
    name: "이노",
    aka: null,
    roles: ["멤버"],
    caption: null,
    color: "#FFFFFF",
    colorLabel: "하얀색",
    oneLiner: "언젠가 이런 날이 올 줄 알았어.",
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@이노2no_1118" }],
    image: null,
    note: null,
  },
  {
    id: "jayeonhyeonsang",
    name: "자연현상",
    aka: "현상",
    roles: ["기획장", "기획", "매니저", "멤버"],
    caption: null,
    color: "#DEDEDE",
    colorLabel: "연한 회색",
    oneLiner: "오이데~",
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@jayeonhyeonsang" }],
    image: "img/members/jayeonhyeonsang.png",
    note: null,
  },
  {
    id: "gomjae",
    name: "곰재",
    aka: null,
    roles: ["멤버"],
    caption: null,
    color: "#000000",
    colorLabel: "검은색",
    oneLiner: "노는게 제일 좋은 청년입니다",
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@gomjae-b5t" }],
    image: "img/members/gomjae.png",
    note: null,
  },
  {
    id: "guengchlieram",
    name: "이람",
    aka: "경칠이람",
    roles: ["멤버", "편집"],
    caption: "유튜브는 낮밤사이 지원과 함께 14개월의 공백기를 깨고 활동을 재개했습니다.",
    color: "#9B687C",
    colorLabel: "시든 마른 장미색 (눈동자, 목걸이)",
    oneLiner: "ABM 야라라라 대히트 치고 봉인 에반데",
    links: [
      { label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@K_72_R" },
      { label: "치지직", icon: "live_tv", url: "https://chzzk.naver.com/991cb034fe860159448e6fd456c4f335" },
      { label: "인스타그램", icon: "photo_camera", url: "https://www.instagram.com/kyeong72ram/" },
    ],
    image: "img/members/guengchlieram.png",
    note: null,
  },
  {
    id: "mokanaria",
    name: "모카나리아",
    aka: "모카",
    roles: ["멤버"],
    caption: null,
    color: null,
    colorLabel: null,
    oneLiner: "으헤헤헤",
    links: [
      { label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@MOKAnaRIA-b9z" },
      { label: "치지직", icon: "live_tv", url: "https://chzzk.naver.com/59723e617a5ee261e4d7c3797bc1e27f" },
    ],
    image: "img/members/mokanaria.png",
    note: null,
  },
  {
    id: "satnoran",
    name: "샛노란",
    aka: "노란",
    roles: ["멤버"],
    caption: null,
    color: "#FFD972",
    colorLabel: null,
    oneLiner: "두마디",
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@샛노란NORAN" }],
    image: "img/members/satnoran.png",
    note: null,
  },
  {
    id: "seoeajin",
    name: "서아진",
    aka: "아진",
    roles: ["멤버"],
    caption: null,
    color: "#ECC2ED",
    colorLabel: "핑크 라벤더",
    oneLiner: "열심히 해봅시다",
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@tjdkwls" }],
    image: "img/members/seoeajin.png",
    note: null,
  },
  {
    id: "piri",
    name: "피리",
    aka: null,
    roles: ["멤버", "컨텐츠 보조"],
    caption: null,
    color: "#311133",
    colorLabel: "다크 마젠타 · 짙고 어두운 보라색",
    oneLiner: "재밌게 잘 놀겠습니다",
    links: [
      { label: "치지직", icon: "live_tv", url: "https://chzzk.naver.com/54e9124f5e6f4d399ec2ad7378ce2d46/about" },
      { label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/channel/UC3zRU9tt_dxhmgZymH1zkfQ" },
    ],
    image: "img/members/piri.png",
    note: null,
  },
  {
    id: "inyoung",
    name: "인영",
    aka: "인 영 / 길우영 / 길인영",
    roles: ["멤버"],
    caption: null,
    color: "#92BB95",
    colorLabel: "연두 · 빨강",
    oneLiner: "즐겁게 놀아봅시다.",
    links: [{ label: "유튜브", icon: "smart_display", url: "https://www.youtube.com/@inyeong0516" }],
    image: "img/members/inyoung.png",
    note: null,
  },
];

module.exports = { MEMBERS };
